title: Ramakrishnan Sundara Raman
email: ramaks@umich.edu
description: >
  Ramakrishnan Sundara Raman, Assistant Professor at the University of California Santa Cruz
baseurl: ""
url: ""
twitter_username: ramakrishnan13s

# Build settings
markdown: kramdown

collections: 
  - publications
  - workshops
