- key: foci2021session
  text: 'I served as a session chair for the HTTPS censorship session at <a href = "https://conferences.sigcomm.org/sigcomm/2021/workshop-foci.html" target = "_blank">ACM SIGCOMM 2021 Workshop on Free and Open Communications on the Internet (FOCI 21)</a>'
  display: 'true'
- key: foci2021pc
  text: 'I served as a technical program committee member for <a href = "https://conferences.sigcomm.org/sigcomm/2021/workshop-foci.html" target = "_blank">ACM SIGCOMM 2021 Workshop on Free and Open Communications on the Internet (FOCI 21)</a>'
  display: 'true'
- key: outreachcseg
  text: 'I have been serving as the outreach chair for <a href = "https://cseg-michigan.github.io/" target = "_blank"> CSEG, the University of Michigan CSE department grad student organization</a> since July 2020.'
  display: 'true'
- key: secrit
  text: 'I served as the lead host for the Michigan CSE <a href = "https://wiki.eecs.umich.edu/secrit/index.php/Main_Page" target = "_blank"> Security Reading Group (SECRIT) </a> from June 2019 - June 2021'
  display: 'false'
